### ISSUE TITLE
Metadata doesn't match numbers in paper

### ISSUE THREAD

**Issue by cmerenstein** [BTopcuoglu/DeepLearning#15]
Hi there,

I'm trying to use the data from this paper for some methods development work, but I'm not sure I understand the metadata properly. The paper states, "n = 490 patients, 261 controls and 229 cases" but I none of the metadata variables break down that way. I looked at the training scripts on this github, and they use dx as the outcome variable, but filter out to only "normal" and "cancer," so it's not 490 patients anymore, and the breakdown of controls and cases aren't 261/229.

Could someone clarify what is the dependent variable these models were trained on?

Thanks!

**Comment by pschloss** [comment]
Sorry for the confusion - the classification was between “normal” and “SRN”. The “cancer”/“SRN” samples were Advanced ademonas and Cancer samples. Normals were everything else. That should match what you’re seeing.

Pat

**Comment by cmerenstein** [comment]
Ah, thanks!
